
---
# tasks file for roles/analysis-tools

- name: system packages | install epel-release
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: system packages | analysis utils
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - parallel
